#! /usr/bin/env bash

# ------------------------------------------------------------------------------
#
# A man page to PDF script.
#
# 03/13/14 
#
# ------------------------------------------------------------------------------

PAGE=${1}
OUTPUT_FILE=${2}
[[ -z ${OUTPUT_FILE} ]] && OUTPUT_FILE="${PAGE}.pdf"

[[ $# -lt 1 ]] && \
    { echo -e "$(basename $0) [manual] [output file]" ; exit 1 ; }

# Check 'man' command.
command -v man >/dev/null 2>&1 || \
    { echo "command 'man' not found, exiting." ; exit 1 ; }

if [[ "${OSTYPE}" == "darwin"* ]] ; then
    command -v pstopdf >/dev/null 2>&1 || \
        { echo "command 'pstopdf' not found, exiting." ; exit 1 ; }
    man -t "${PAGE}" | pstopdf -i -o "${OUTPUT_FILE}"
elif [[ "${OSTYPE}" == "linux-gnu" || "${OSTYPE}" == "freebsd"* ]] ; then
    command -v ps2pdf >/dev/null 2>&1 || \
        { echo "command 'ps2pdf' not found, exiting." ; exit 1 ; }
    man -t "${PAGE}" | ps2pdf - > "${OUTPUT_FILE}"
else
    echo "Not supported OS type: ${OSTYPE}"
    exit 1
fi

echo "File ${OUTPUT_FILE} generated."
