#! /usr/bin/env zsh

# ------------------------------------------------------------------------------
# 
# run mbsync to check email periodically.
#
# 12/22/16
#
# yqm_leaf@163.com
#
# ------------------------------------------------------------------------------

source "${0:a:h}/lib"

# check interval in minute.
chk_interval=${1:-5}
while : ; do
    mbsync -a || echo "Looks like previous check had some error"
    echo "sleeping for $chk_interval mins, current time: $(date +'%D %T')"
    echo "time left (in sec) to repoll:"
    count_down $(($chk_interval * 60))
done
