#! /usr/bin/env zsh

# ------------------------------------------------------------------------------
#
# Get tips from 'commandlinefu' & send mail.
# 
# NO. of tips: default to 10.  Or the first argument of the script.
#
# 12/25/16
#
# yqm_leaf@163.com
#
# ------------------------------------------------------------------------------

RECEIVER="tim.ye0@aliyun.com"
NO_OF_TIPS="${1:-10}"
TMP_FILE="$(mktemp)" || \
    # could this happen?
    { echo "error creating tmp file for emailing, aborting." >&2 ; exit 2 ; }
#
# Get a line from commandlinefu.com.
#
get_cmd () {
    wget -qO - http://www.commandlinefu.com/commands/random/plaintext | \
        # get rid of header, empty line & ads.
        sed '/commandlinefu\.com/d;/^$/d;/AD/d'
}

mail_sub="commandlinefu"
for i in $(seq 1 $NO_OF_TIPS) ; do

    # A tip example.
    #
    # - # Passwordless mysql{,dump,admin} via my.cnf file
    #   echo -e "[client]
    #   user = YOURUSERNAME
    #   password = YOURPASSWORD" > ~/.my.cnf

    tip="$(get_cmd)" || echo "error getting tip" >&2
    # set message subject to first tip title.  Otherwise the subject would be
    # the same, which is quite boring.
    [[ $i == 1 ]] && \
        mail_sub="$mail_sub: $(echo $tip | sed -n '/#/p' | sed 's/# //')" ;
    echo "$tip" >> "$TMP_FILE"
done

mutt -s "$mail_sub" -- "$RECEIVER" < $TMP_FILE || echo "send mail failed" >&2
rm -f "$TMP_FILE"
