#! /usr/bin/env zsh

# ------------------------------------------------------------------------------
#
# A configuration file. 
#
# 01/02/17
#
# yqm_leaf@163.com
# 
# ------------------------------------------------------------------------------

EMAIL_RECEIVER='tim.ye0@aliyun.com'
DEFAULT_EXIT_CODE=127
LOGFILE="${0:a:h}/logfile"
