#! /usr/bin/env bash

# ------------------------------------------------------------------------------
# 
# This will make a full block blinking cursor inside tmux.
#
# 12/21/16
#
# yqm_leaf@163.com
#
# ------------------------------------------------------------------------------

F="/tmp/terminfo"
infocmp > "$F"
sed -i 's/\?0c/\?6c/'"$F"
tic "$F"
