#! /usr/bin/env tclsh
#
# ------------------------------------------------------------------------------
#
# Tcl library.
# 
# yeqiming@gmail.com
#
# 01/27/13
# ------------------------------------------------------------------------------

package require Expect

#
# ssh auto login.
#
proc _ssh {ip user pass {timeout ""}} {
    global _prompt

    spawn ssh -l $user $ip

    expect {
        -re "yes/no" {
            send "yes\r"
            exp_continue
        }
        -re ".*ssword" {
            send "$pass\r"
            exp_continue
        }
        -re "$_prompt" {}
        eof {
            puts stderr "Login ended."
        } timeout {
            puts stderr "Login timeout."
        }
    }

    return $spawn_id
}

#
# Check if input is a valid IPv4 address.
#
proc valid_ipv4 {ip} {
    if {[regexp {^([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})$} $ip -\
        b1 b2 b3 b4]} {
            foreach byte "$b1 $b2 $b3 $b4" {
                if {$byte > 255} { return false }
            }
            return 0
        }
    return 1
}

#
# Read file.
#
proc read_file {f} {

    if {![file readable $f]} {
        return 1
    }

    set fd [open $f r]
    set d [read $fd]
    close $fd
    return $d
}
